name: build

on: push

jobs:

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        architecture: [linux-arm-v7, linux-arm64, linux-amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shellcheck
        run: |
          shellcheck --version
          if [[ -d ./root ]]; then
            find "./root" -type f -print -exec shellcheck {} \;
          else
            true
          fi

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

      - name: Build images using buildx
        run: |
          ARCHITECTURE=${{ matrix.architecture }}
          docker buildx build \
            --cache-from "${GITHUB_REPOSITORY//docker-/}:${GITHUB_REF//refs\/heads\//}-cache-${ARCHITECTURE}" \
            --cache-to "${GITHUB_REPOSITORY//docker-/}:${GITHUB_REF//refs\/heads\//}-cache-${ARCHITECTURE}" \
            --platform ${ARCHITECTURE//-/\/} \
            --output "type=image,push=true" \
            --tag ${GITHUB_REPOSITORY//docker-/}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-${GITHUB_RUN_NUMBER}-${ARCHITECTURE} \
            --build-arg LABEL_CREATED="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            --build-arg LABEL_TITLE="${GITHUB_REPOSITORY//docker-/}:${GITHUB_REF//refs\/heads\//}" \
            --build-arg LABEL_REVISION="${GITHUB_SHA}" \
            --build-arg LABEL_SOURCE="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/tree/${GITHUB_REF//refs\/heads\//}" \
            --build-arg LABEL_VENDOR="${GITHUB_REPOSITORY%/*}" \
            --build-arg LABEL_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/blob/master/README.md" \
            --build-arg LABEL_VERSION="${SONARR_VERSION=3.0.3.913}" \
            --build-arg SONARR_VERSION="${SONARR_VERSION=3.0.3.913}" \
            --build-arg PACKAGE_VERSION="${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-${GITHUB_RUN_NUMBER}" \
            --file ./${ARCHITECTURE}.Dockerfile ./

      - name: Push to GitHub registry
        env:
          DOCKER_USERNAME: ${GITHUB_REPOSITORY%/*}
          DOCKER_PASSWORD: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login ghcr.io --username "${DOCKER_USERNAME}" --password-stdin
          docker pull ${GITHUB_REPOSITORY//docker-/}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-${GITHUB_RUN_NUMBER}-${{ matrix.architecture }}
          docker tag ${GITHUB_REPOSITORY//docker-/}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-${GITHUB_RUN_NUMBER}-${{ matrix.architecture }} ghcr.io/${GITHUB_REPOSITORY//docker-/}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-${GITHUB_RUN_NUMBER}-${{ matrix.architecture }}
          docker push ghcr.io/${GITHUB_REPOSITORY//docker-/}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-${GITHUB_RUN_NUMBER}-${{ matrix.architecture }}

      - name: Prepare for tests
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: List installed packages
        run: |
          docker run --rm --entrypoint="" ${GITHUB_REPOSITORY//docker-/}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-${GITHUB_RUN_NUMBER}-${{ matrix.architecture }} apt list --installed

      - name: Check if app works
        run: |
          app_url="http://localhost:8989/system/status"
          docker run --rm --network host -d --name service -e DEBUG="yes" ${GITHUB_REPOSITORY//docker-/}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-${GITHUB_RUN_NUMBER}-${{ matrix.architecture }}
          currenttime=$(date +%s); maxtime=$((currenttime+60)); while (! curl -fsSL "${app_url}" > /dev/null) && [[ "$currenttime" -lt "$maxtime" ]]; do sleep 1; currenttime=$(date +%s); done
          curl -fsSL "${app_url}" > /dev/null

      - name: Show docker logs
        if: always()
        run: |
          docker logs service

  publish:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Enable experimental
        run: |
          mkdir ~/.docker && echo '{"experimental": "enabled"}' > ~/.docker/config.json

      - name: Login to docker registry
        env:
          DOCKER_USERNAME_DOCKERHUB: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD_DOCKERHUB: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USERNAME_GITHUB: ${GITHUB_REPOSITORY%/*}
          DOCKER_PASSWORD_GITHUB: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          echo "${DOCKER_PASSWORD_DOCKERHUB}" | docker login docker.io --username "${DOCKER_USERNAME_DOCKERHUB}" --password-stdin
          echo "${DOCKER_PASSWORD_GITHUB}" | docker login ghcr.io --username "${DOCKER_USERNAME_GITHUB}" --password-stdin

      - name: Create docker manifests
        run: |
          registries=(docker.io ghcr.io)
          for registry in ${registries[*]}; do
            TAG_BASE="${GITHUB_REPOSITORY//docker-/}:${GITHUB_REF//refs\/heads\//}"
            TAG="${TAG_BASE}-${GITHUB_SHA:0:7}-${GITHUB_RUN_NUMBER}"
            docker manifest create ${registry}/${TAG_BASE} --amend ${registry}/${TAG}-linux-amd64 --amend ${registry}/${TAG}-linux-arm-v7 --amend ${registry}/${TAG}-linux-arm64
            docker manifest push   ${registry}/${TAG_BASE}
            docker manifest create ${registry}/${TAG_BASE}-${SONARR_VERSION=3.0.3.913} --amend ${registry}/${TAG}-linux-amd64 --amend ${registry}/${TAG}-linux-arm-v7 --amend ${registry}/${TAG}-linux-arm64
            docker manifest push   ${registry}/${TAG_BASE}-${SONARR_VERSION=3.0.3.913}
            docker manifest create ${registry}/${TAG_BASE}-${GITHUB_SHA:0:7} --amend ${registry}/${TAG}-linux-amd64 --amend ${registry}/${TAG}-linux-arm-v7 --amend ${registry}/${TAG}-linux-arm64
            docker manifest push   ${registry}/${TAG_BASE}-${GITHUB_SHA:0:7}
            if [[ ${GITHUB_REF//refs\/heads\//} == stable ]]; then
              docker manifest create ${registry}/${GITHUB_REPOSITORY//docker-/}:latest --amend ${registry}/${TAG}-linux-amd64 --amend ${registry}/${TAG}-linux-arm-v7 --amend ${registry}/${TAG}-linux-arm64
              docker manifest push   ${registry}/${GITHUB_REPOSITORY//docker-/}:latest
            fi
          done

      - name: Take screenshot
        run: |
          app_url="http://localhost:8989/system/status"
          docker run --rm --network host -d --name service -e DEBUG="yes" ${GITHUB_REPOSITORY//docker-/}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}
          currenttime=$(date +%s); maxtime=$((currenttime+60)); while (! curl -fsSL "${app_url}" > /dev/null) && [[ "$currenttime" -lt "$maxtime" ]]; do sleep 1; currenttime=$(date +%s); done
          docker run --rm --network host --entrypoint="" -u $(id -u $USER) -v ${GITHUB_WORKSPACE}:/usr/src/app/src zenika/alpine-chrome:with-puppeteer node src/puppeteer.js

      - name: Send discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -u "${GITHUB_REPOSITORY%/*}:${GITHUB_TOKEN}" -fsSL https://gist.githubusercontent.com/${GITHUB_REPOSITORY%/*}/3d98159d47e0bf5eccbff221f1288472/raw/discord-action-notify.sh > discord-action-notify.sh
          export VERSION_FIELD=${SONARR_VERSION=3.0.3.913} && bash discord-action-notify.sh
